// DOM.js
//
// Internal DOM representation for CanvasBrowser

class BrowserNode {

    constructor(type, tag = null) {

        this.type = type;
        this.tag = tag;

        this.parent = null;
        this.children = [];

        this.attributes = {};

        this.style = {};

        this.text = "";

        // Generated by Layout.js later
        this.layout = {
            x: 0,
            y: 0,
            width: 0,
            height: 0
        };

        // Interaction state
        this.hover = false;
        this.focus = false;

    }


    appendChild(node) {

        node.parent = this;
        this.children.push(node);

    }


    getAttribute(name) {

        return this.attributes[name];

    }


    setAttribute(name, value) {

        this.attributes[name] = value;

    }


    hasAttribute(name) {

        return (
            name in this.attributes
        );

    }


    find(tagName) {

        const results = [];

        if (
            this.tag === tagName
        ) {
            results.push(this);
        }


        for (const child of this.children) {

            results.push(
                ...child.find(tagName)
            );

        }


        return results;

    }

}



class DOMTree {

    constructor(document) {

        this.root =
            this.parseNode(
                document.body
            );

    }



    parseNode(domNode) {


        if (!domNode)
            return null;


        /*
            Text node
        */
        if (
            domNode.nodeType ===
            Node.TEXT_NODE
        ) {

            const node =
                new BrowserNode(
                    "text"
                );


            node.text =
                domNode.textContent;


            return node;

        }



        /*
            Ignore:
            comments,
            scripts,
            unsupported nodes
        */
        if (
            domNode.nodeType !==
            Node.ELEMENT_NODE
        ) {

            return null;

        }



        const node =
            new BrowserNode(
                "element",
                domNode.tagName
                .toLowerCase()
            );



        /*
            Copy attributes
        */
        for (
            const attribute
            of domNode.attributes
        ) {

            node.attributes[
                attribute.name
            ] =
                attribute.value;

        }



        /*
            Parse inline CSS
        */
        if (
            node.attributes.style
        ) {

            node.style =
                this.parseStyle(
                    node.attributes.style
                );

        }



        /*
            Children
        */
        for (
            const child
            of domNode.childNodes
        ) {

            const parsed =
                this.parseNode(child);


            if (parsed) {

                node.appendChild(
                    parsed
                );

            }

        }


        return node;

    }



    parseStyle(styleText) {

        const style = {};


        const rules =
            styleText.split(";");


        for (const rule of rules) {

            const parts =
                rule.split(":");


            if (
                parts.length !== 2
            ) {
                continue;
            }


            const key =
                parts[0]
                .trim();


            const value =
                parts[1]
                .trim();


            style[key] = value;

        }


        return style;

    }

}

window.BrowserNode = BrowserNode;
window.DOMTree = DOMTree;